### ISSUE TITLE
strtotime() and date() functions

### ISSUE THREAD

**Issue by chimeno** [wanze/Google-Analytics-API-PHP#3]
I'm getting this after trying to run my script:

> Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are >_required_ to use the date.timezone setting or the date_default_timezone_set() >function. In case you used any of those methods and you are still getting this >warning, you most likely misspelled the timezone identifier. We selected >'Europe/Berlin' for 'CEST/2.0/DST' instead in >/path/to/GoogleAnalytics>API.class.php on line 68```
> 
> Warning: date(): It is not safe to rely on the system's timezone settings. You are >_required_ to use the date.timezone setting or the date_default_timezone_set() >function. In case you used any of those methods and you are still getting this >warning, you most likely misspelled the timezone identifier. We selected >'Europe/Berlin' for 'CEST/2.0/DST' instead in >/path/to/GoogleAnalyticsAPI.class.php on line 68

php -v

> PHP 5.3.15 with Suhosin-Patch (cli) (built: Aug 24 2012 17:45:44) 
> Copyright (c) 1997-2012 The PHP Group
> Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

Maybe a default timezone with a 'global' variable should be enough.
Great class anyway :)

**Comment by wanze** [comment]
Hi chimeno,
Thanks for reporting this!
Could it be that you haven't set a valid timezone setting in your php.ini?
http://php.net/manual/en/function.date-default-timezone-set.php

Setting a default timezone would be a solution - but then everyone not living in this zone needs to adjust the config. Maybe it would be simpler in this case to just surpress the warnings by prepending '@' to the date/strtotime functions... :)
