### ISSUE TITLE
Not receiving 'access token' with all the right credentials

### ISSUE THREAD

**Issue by skyserpent** [wanze/Google-Analytics-API-PHP#8]
Hey there, here's the error I'm receiving when using the basic example:

Sorry, something wend wrong retrieving the oAuth tokens

I've entered my credentials as according to API Console and for some reason I'm not getting an access token.

**Comment by pyerro** [comment]
It could be a problem with CURL request. In the GoogleAnalyticsAPI.class.php > class Http > function curl (around line 720) add one more option to stop CURL from verifying the peer's certificate:

curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

**Comment by wanze** [comment]
@skyserpent Did the suggestion by pyerro fix your issue?

**Comment by itailulu** [comment]
@skyserpent the suggestion by pyerro worked perfectly for me!
Thanks!

**Comment by wanze** [comment]
:+1:
